### ISSUE TITLE
[bug] Server-side webpack does not recognize `transpileDependencies` option in `vue.config.js`

### ISSUE THREAD

**Issue by beeplin** [Akryum/vue-cli-plugin-ssr#25]
I am using the [quasar plugin](https://github.com/quasarframework/vue-cli-plugin-quasar) with ssr. Quasar plugin added `{  transpileDependencies: [/[\\/]node_modules[\\/]quasar-framework[\\/]/], }` in `vue.config.js` since its source code in `node_modules` is ES6 and has lots of 'import's. 

Without adding `vue add @akryum/ssr` it works fine; after adding ssr, the server side wepback does not know the quasar module should be transpiled and gives an error like: 

```
(function (exports, require, module, __filename, __dirname) { import BtnMixin from './btn-mixin.js'
                                                                     ^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at r (C:\Users\beep\git\c42v4\node_modules\vue-server-renderer\build.js:8346:16)
    at Object.quasar-framework/src/components/btn/QBtn.js (webpack:/external "quasar-framework/src/components/btn/QBtn.js":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../src/main.js (main.js:1317:101)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../src/entry-server.js (main.js:1220:63)
``` 

Is there a way to add `transpileDependencies` to server-side webpack?

**Comment by beeplin** [comment]
It turns out to be not because the `transpileDependencies`, but because quasar is using a webpack alias `quasar` instead the real npm package name `quasar-framework`. After digging into the undocumented details in the source code, I figured out it can be handled by add such an option in `vue.config.js`: 

```js
// vue.config.js
...
  pluginOptions: {
    ssr: {
      nodeExternalsWhitelist: [/\.css$/, /\?vue&type=style/, /quasar/], // HERE IS THE TRICK
    },
  },
...
```

And what's more, in order to enable ssr for quasar, the `main.js` must add `Quasar.ssrUpdate` before `new Vue(...)`, like this:

```js
// main.js

...
export async function createApp({ context, beforeApp = () => {}, afterApp = () => {} } = {}) {

  ...

  await beforeApp({
    router,
    store,
    apolloProvider,
  })

  const appOptions = { // DEFINE THE OPTIONS FOR THE APP
    router,
    store,
    apolloProvider,
    render: h => h(App),
  }

  Quasar.ssrUpdate({ app: appOptions, ssr: context }) // CALL Quasar.ssrUpdate with the options 

  const app = new Vue(appOptions) // THEN new Vue()

  const result = {
    app,
    router,
    store,
    apolloProvider,
  }

  await afterApp(result)

  return result
}
```
