### ISSUE TITLE
Docker Alpine Image - clipboardy & xcel

### ISSUE THREAD

**Issue by kdmcclel** [Akryum/vue-cli-plugin-ssr#40]
Having this issue with docker alpine image:
```
  - Local:   http://localhost:8080 (copied to clipboard)
(node:27) UnhandledPromiseRejectionWarning: Error: Couldn't find the required `xsel` binary. On Debian/Ubuntu you can install it with: sudo apt install xsel
    at handler (/usr/src/app/node_modules/clipboardy/lib/linux.js:7:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:27) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

```

**Comment by hmillison** [comment]
I'm also seeing this issue in my docker container. Would like to avoid adding this dependency for functionality i don't need.
