### ISSUE TITLE
Problem with vue-cli-plugin-vuetify

### ISSUE THREAD

**Issue by oceandrama** [Akryum/vue-cli-plugin-ssr#45]
After adding this plugin over `vue-cli-plugin-vuetify` and `vue-cli-plugin-apollo` I I get the following error on `ssr:serve`

```
...\node_modules\vuetify\lib\index.js:1
(function (exports, require, module, __filename, __dirname) { import Vuetify from './components/Vuetify';
                                                                     ^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at r (E:\Projects\ready\frontend\node_modules\vue-server-renderer\build.js:8365:16)
    at Object.vuetify/lib (webpack:/external "vuetify/lib":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../src/App.vue (src/App.vue:1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../src/entry-server.js (app.js:1492:66)
```

**Comment by Skyhark-Projects** [comment]
Hi,

That's because the server bundle does not parse Vuetify. It keeps it as an external dependency while node does not support imports (only in experimental mode yet).
So you need to tell to your config file that Vuetify has to be parsed and included into your server bundle.

You can add veutify in the nodeExternalsWhitelist config parameter like this:

```
module.exports = {
    pluginOptions: {
        ssr: {
            entry: target => `./src/entry-${target}`,
            favicon: './public/img/favicon.png',
            nodeExternalsWhitelist: [/\.css$/, /\?vue&type=style/, /^vuetify/, /^register-service-worker/],
```

**Comment by svewag** [comment]
thanks, this solution also helped my out when using bootstrap-vue :-)
